### ISSUE TITLE
Ethernet padding is interpreted as a TCP payload

### ISSUE THREAD

**Issue by irl** [nevil-brownlee/python-libtrace#10]
Ethernet requires that all packets be at least 60 bytes long (64 bytes if you include the Frame Check Sequence at the end), so if a packet is less than 60 bytes long (including the 14-byte Ethernet header), additional padding bytes have to be added to the end of the packet.

When a TCP control packet is sent with no payload and this is captured, python-libtrace will treat the Ethernet padding as a TCP payload and return that instead of None, even though the TCP header specifies a zero payload length.

**Comment by irl** [comment]
Ah, I see there is no length for the TCP header. So this is probably a bug in the Ethernet handling.

**Comment by nevil-brownlee** [comment]
Hi Iain:

I have some time available to work on python-libtrace, and I've
asked my Waikato colleagues about SCTP in libtrace.  Two questions
for you:

1. Can you email me some packet traces with the kind of SCTP sessionsd
    in them that you're working with, please?

2. Can you give me a bit more information about what, exactly, you'd
    like to see for SCTP dissection.   A list of the functions you
    need would be a good starting point for me.

Cheers, Nevil

-- 
---------------------------------------------------------------------
  Nevil Brownlee                          Computer Science Department
  Phone: +64 9 373 7599 x88941             The University of Auckland
  FAX: +64 9 373 7453   Private Bag 92019, Auckland 1142, New Zealand

**Comment by irl** [comment]
Have replied to the above comment on the relevant issue, #3.

**Comment by nevil-brownlee** [comment]
Fixed: packet.tcp_payload (and packet.udp_payload) didn't check for zero payload length.
They now return None for zero-length payloads.
