### ISSUE TITLE
No support for SCTP

### ISSUE THREAD

**Issue by irl** [nevil-brownlee/python-libtrace#3]
Please consider adding support for SCTP dissection to allow for mami-project/pathspider#4 to be properly implemented.

SCTP dissection support already exists in libtrace.

**Comment by nevil-brownlee** [comment]
Looking at the WAND Doxygen page for Libtrace, it looks to me as though SCTP is only mentioned as a value for IP protocol.  Can you outline what you'd like to see in SCTP for me, please?

Cheers,  Nevil

**Comment by irl** [comment]
source port and destination port in order to at least perform flow matching in pathspider, though I guess I've misread the libtrace docs, I guess it has no idea what chunks are and no idea how to dissect them, so that would end up being implemented in python and being not terribly fast...

**Comment by nevil-brownlee** [comment]
I'll put some time into SCTP real soon now (probably by doing in pypy-libtrace first).
To help me test that, could you email me ( Nevil Brownlee n.brownlee@auckland.ac.nz ) a sample pcap file with, say about 1,000 SCTP records in it, please?
BTW, pypy-libtrace runs python 2 code a lot faster that python-libtrace; alas there doesn't seem to be a version of pypy that supports python 3 yet.

**Comment by irl** [comment]
I think we would want the following:

* extract port numbers
* extract verification tag
* extract checksum
* get an array of chunks
  * get chunk type
  * get chunk flags
  * get chunk length
  * get chunk payload

https://wiki.wireshark.org/SampleCaptures#Stream_Control_Transmission_Protocol_.28SCTP.29 has sample traces.

It would be nice if some chunks were dissectable but if the basics are there then any further dissection can be done in Python as we currently do for TCP options. Getting the ability to isolate just one chunk would make that further dissection a lot easier.

**Comment by nevil-brownlee** [comment]
OK, I've implemented SCTP dissection, as you requested.  It's documents in doc/SCTP.html
