### ISSUE TITLE
Everything hangs if you try to listen on an interface that isn't up

### ISSUE THREAD

**Issue by irl** [nevil-brownlee/python-libtrace#4]
Discovered in mami-project/pathspider#16. No longer affects pathspider as we check the interface status before starting the observer. Still a problem with python-libtrace though.

**Comment by nevil-brownlee** [comment]
I don't think libtrace provides a way to check that an interface is up it expects a URI for the interface, then starts a trace.  It would be possible to catch this with a timeout, or maybe some other way.
How do you do it for pathspider?

Cheers, Nevil

**Comment by irl** [comment]
https://github.com/mami-project/pathspider/blob/master/pathspider/network/__init__.py#L4

Introduces a dependency on pyroute2 which we're going to need later anyway as we're running on testbeds with multihomed hosts. It may be possible to do some kind of raw netfilter message to determine only if the interface is up. A timeout also isn't a terrible idea and is cross-platform, everything supports time, even GNU Hurd.

**Comment by nevil-brownlee** [comment]
I've now implemented trace.conf_timeout(integer), so that inactive interfaces can time out using libtrace events.  For example, for a trace with URI int"eth0", conf_timeout(10) will time out if it sees no packets on interface int:eth0 for 10 seonds.
