### ISSUE TITLE
pldns doesn't like TCP payloads

### ISSUE THREAD

**Issue by irl** [nevil-brownlee/python-libtrace#8]
```
dns = ldns(tcp.payload)
```

Even when the payload fits inside a single packet, this seems to fail, but the documentation suggests it should work.

The offending packet can be found in here:

https://github.com/mami-project/pathspider/blob/master/pathspider/tests/data/dns_valid_response_tcp.pcap

**Comment by nevil-brownlee** [comment]
pldns.ldns() expected a UDP payload, and not a TCP payload.
I've added code to it to recognise that it came from a TCP packet; in that case it skips DNS record length (first two payload bytes).
I've also added a test case for this, using your tcp.dns pcap file.
Thanks very much for reporting this bug!
Cheers, Nevil
